## Used for storing a matrix in an object that provides methods for solving
## for the inverse matrix. Stores results in a cache for faster repeated calls.

## Generates an object contanining methods for inverting a matrix
## and caching the result to speed up repeated calls

makeCacheMatrix <- function(x = matrix()) {
     m <- NULL    ## resets the cache
     set <- function(y) {
          x <<- y
          m <<- NULL
     }
     get <- function() x    ## returns the original matrix
     setinverse <- function(solve) m <<- solve
          ## called by cacheSolve to solve the inverse matrix
          ## and store it in the cache
     getinverse <- function() m    ## returns what is stored in the cache
     list(set = set, get = get,    ## This list identifies the internal 
          setinverse = setinverse,    ## functions used by cacheSolve
          getinverse = getinverse)    
}


## Finds the inverse of a matrix generated by makeCacheMatrix
## and caches it. If the inverse is already stored in the cache,
## the function will provide that value with a message explaining
## that behavior

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
     m <- x$getinverse()    ## check to see if the cache contains the inverse
     if(!is.null(m)) {    ## if it does...
          message("getting cached data")    ## display this message
          return(m)    ## and return the inverse matrix
     }    
     data <- x$get()    ## if no inverse was found, pulls the original matrix...
     m <- solve(data, ...)    ## and calculates the inverse... 
     x$setinverse(m)    ## stores it in in the cache...
     m    ## then returns the inverse.
}
